name: Deploy Development to Production

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Production Server
        run: |
          ssh -o StrictHostKeyChecking=no user@10.24.5.66 "
            cd /home/user/hr_github &&
            git fetch --all &&
            git reset --hard origin/development &&
            git pull origin development &&

            /usr/local/go/bin/go build -o hrserver main.go &&
            sudo systemctl restart hr.service &&
            echo '✅ Deployment to production complete!'
          "

